"""initial schema

Revision ID: 3b5a881ed542
Revises: 
Create Date: 2026-08-13 13:52:29.702401

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assets',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assets_type'), 'assets', ['type'], unique=False)
    op.create_table('coordination_runs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('triggered_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('trigger_reason', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('grid_snapshot', sa.JSON(), nullable=True),
    sa.Column('summary', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('policies',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('threshold_kw', sa.Float(), nullable=True),
    sa.Column('threshold_percent', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_policies_type'), 'policies', ['type'], unique=False)
    op.create_table('allocations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('coordination_run_id', sa.String(), nullable=False),
    sa.Column('asset_id', sa.String(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('allocated_power_kw', sa.Float(), nullable=True),
    sa.Column('target_soc_percent', sa.Float(), nullable=True),
    sa.Column('feasible', sa.Boolean(), nullable=False),
    sa.Column('reason', sa.String(), nullable=False),
    sa.Column('source_intent_id', sa.String(), nullable=True),
    sa.Column('constraints_considered', sa.JSON(), nullable=False),
    sa.Column('sequence_no', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['coordination_run_id'], ['coordination_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_allocations_asset_id'), 'allocations', ['asset_id'], unique=False)
    op.create_index(op.f('ix_allocations_coordination_run_id'), 'allocations', ['coordination_run_id'], unique=False)
    op.create_table('capabilities',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('asset_id', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('max_power_kw', sa.Float(), nullable=False),
    sa.Column('min_power_kw', sa.Float(), nullable=False),
    sa.Column('capacity_kwh', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('asset_id', 'type', name='uq_capability_asset_type')
    )
    op.create_index(op.f('ix_capabilities_asset_id'), 'capabilities', ['asset_id'], unique=False)
    op.create_table('impacts',
    sa.Column('coordination_run_id', sa.String(), nullable=False),
    sa.Column('grid_import_reduction_kw', sa.Float(), nullable=True),
    sa.Column('renewable_utilization_percent', sa.Float(), nullable=True),
    sa.Column('peak_demand_reduction_kw', sa.Float(), nullable=True),
    sa.Column('curtailed_energy_kwh', sa.Float(), nullable=True),
    sa.Column('critical_load_served_percent', sa.Float(), nullable=True),
    sa.Column('battery_reserve_maintained', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['coordination_run_id'], ['coordination_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('coordination_run_id')
    )
    op.create_table('intents',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('asset_id', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('target_soc_percent', sa.Float(), nullable=True),
    sa.Column('deadline', sa.DateTime(timezone=True), nullable=True),
    sa.Column('min_soc_percent', sa.Float(), nullable=True),
    sa.Column('min_power_kw', sa.Float(), nullable=True),
    sa.Column('window_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('window_end', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_intents_asset_id'), 'intents', ['asset_id'], unique=False)
    op.create_table('telemetry',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('asset_id', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('power_kw', sa.Float(), nullable=False),
    sa.Column('energy_kwh', sa.Float(), nullable=True),
    sa.Column('soc_percent', sa.Float(), nullable=True),
    sa.Column('available', sa.Boolean(), nullable=False),
    sa.Column('operating_state', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_telemetry_asset_id'), 'telemetry', ['asset_id'], unique=False)
    op.create_index(op.f('ix_telemetry_timestamp'), 'telemetry', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_telemetry_timestamp'), table_name='telemetry')
    op.drop_index(op.f('ix_telemetry_asset_id'), table_name='telemetry')
    op.drop_table('telemetry')
    op.drop_index(op.f('ix_intents_asset_id'), table_name='intents')
    op.drop_table('intents')
    op.drop_table('impacts')
    op.drop_index(op.f('ix_capabilities_asset_id'), table_name='capabilities')
    op.drop_table('capabilities')
    op.drop_index(op.f('ix_allocations_coordination_run_id'), table_name='allocations')
    op.drop_index(op.f('ix_allocations_asset_id'), table_name='allocations')
    op.drop_table('allocations')
    op.drop_index(op.f('ix_policies_type'), table_name='policies')
    op.drop_table('policies')
    op.drop_table('coordination_runs')
    op.drop_index(op.f('ix_assets_type'), table_name='assets')
    op.drop_table('assets')
    # ### end Alembic commands ###
